#!/usr/bin/env python3
"""Extract the Sharp BASIC keyword/token tables from the Java sources and emit src/keywords.rs.

One-time / on-demand generator. The Rust project is otherwise independent of the Java
`SharpBasicShared` project; rerun this only when the Java keyword tables change.

Usage:
    python3 tools/extract_keywords.py [--check]
    SHARP_BASIC_SHARED=/path/to/SharpBasicShared python3 tools/extract_keywords.py

--check  : regenerate to stdout diff instead of writing (exit 1 if out of date).

Source of truth:
    <SharpBasicShared>/sharp-basic-core/src/main/java/ch/erzberger/sharpbasic/core/keyword/
        device/{Pc1500,Ce150,Ce158,Pc1600}Keywords.java

The two emitted pools follow Java `KeywordRegistry` pool order exactly, so a Rust
`Registry` that inserts them in slice order and lets later inserts win reproduces the
Java name/code lookup semantics:
    PC1500_SET = Pc1500 ++ Ce150 ++ Ce158           (forPc1500(): {PC1500, CE150, CE158})
    PC1600_SET = Ce150 ++ Ce158 ++ Pc1600           (forPc1600(): {CE150, CE158, PC1600})
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
OUT = PROJECT / "src" / "keywords.rs"

CATEGORY_RS = {
    "PC1500": "Category::Pc1500",
    "CE150_EXTENSION": "Category::Ce150",
    "CE158_EXTENSION": "Category::Ce158",
    "PC1600": "Category::Pc1600",
}
KIND_RS = {
    "STATEMENT": "Kind::Statement",
    "FUNCTION": "Kind::Function",
    "OPERATOR": "Kind::Operator",
    "MODIFIER": "Kind::Modifier",
}

# new BasicKeyword("NAME", "ABBR", 0xF097, PC1500, STATEMENT)
#   or             ("NAME",         0xF097, PC1500, STATEMENT)
CALL_RE = re.compile(
    r'new\s+BasicKeyword\s*\(\s*'
    r'"((?:[^"\\]|\\.)*)"\s*,\s*'                 # name
    r'(?:"((?:[^"\\]|\\.)*)"\s*,\s*)?'            # optional abbreviation
    r'(0[xX][0-9A-Fa-f]+)\s*,\s*'                 # token code
    r'([A-Z0-9_]+)\s*,\s*'                        # category (static-imported bare name)
    r'([A-Z0-9_]+)\s*\)',                         # type
)


def find_shared() -> Path:
    env = os.environ.get("SHARP_BASIC_SHARED")
    candidates = []
    if env:
        candidates.append(Path(env))
    candidates.append(PROJECT.parent / "SharpBasicShared")
    for c in candidates:
        if (c / "sharp-basic-core").is_dir():
            return c
    raise SystemExit(
        "SharpBasicShared not found. Set SHARP_BASIC_SHARED or place it next to this project."
    )


def java_str_to_rust(s: str) -> str:
    # Names/abbreviations are plain ASCII (PRINT, CHR$, PEEK#, //). Keep Java escapes as-is;
    # none of the current entries actually use a backslash.
    return s


def parse_file(path: Path):
    text = path.read_text(encoding="utf-8")
    out = []
    for m in CALL_RE.finditer(text):
        name, abbr, code_hex, cat, kind = m.groups()
        abbr = abbr if abbr is not None else name
        if cat not in CATEGORY_RS:
            raise SystemExit(f"{path.name}: unknown category {cat!r} for {name!r}")
        if kind not in KIND_RS:
            raise SystemExit(f"{path.name}: unknown type {kind!r} for {name!r}")
        code = int(code_hex, 16)
        if not (0 <= code <= 0xFFFF):
            raise SystemExit(f"{path.name}: token code out of range for {name!r}: {code_hex}")
        out.append(
            dict(name=name, abbr=abbr, code=code, cat=CATEGORY_RS[cat], kind=KIND_RS[kind])
        )
    if not out:
        raise SystemExit(f"{path.name}: no `new BasicKeyword(...)` entries matched")
    return out


def emit_slice(name: str, doc: str, entries: list[dict]) -> str:
    lines = [f"/// {doc}", f"pub static {name}: &[Keyword] = &["]
    for e in entries:
        nm = java_str_to_rust(e["name"])
        ab = java_str_to_rust(e["abbr"])
        lines.append(
            f'    Keyword {{ name: "{nm}", abbrev: "{ab}", '
            f'code: 0x{e["code"]:04X}, category: {e["cat"]}, kind: {e["kind"]} }},'
        )
    lines.append("];")
    return "\n".join(lines)


def build() -> str:
    shared = find_shared()
    dev = (
        shared
        / "sharp-basic-core/src/main/java/ch/erzberger/sharpbasic/core/keyword/device"
    )
    pc1500 = parse_file(dev / "Pc1500Keywords.java")
    ce150 = parse_file(dev / "Ce150Keywords.java")
    ce158 = parse_file(dev / "Ce158Keywords.java")
    pc1600 = parse_file(dev / "Pc1600Keywords.java")

    try:
        commit = subprocess.check_output(
            ["git", "-C", str(shared), "rev-parse", "--short", "HEAD"], text=True
        ).strip()
    except Exception:
        commit = "unknown"

    pc1500_set = pc1500 + ce150 + ce158
    pc1600_set = ce150 + ce158 + pc1600

    header = f"""// @generated by tools/extract_keywords.py — DO NOT EDIT.
// Source: SharpBasicShared @ {commit}
//   sharp-basic-core/.../keyword/device/{{Pc1500,Ce150,Ce158,Pc1600}}Keywords.java
// Regenerate: python3 tools/extract_keywords.py
//
// Pool order matches Java `KeywordRegistry` so that inserting in slice order with
// "later wins" reproduces its name/code lookup:
//   PC1500_SET = Pc1500 ++ Ce150 ++ Ce158
//   PC1600_SET = Ce150 ++ Ce158 ++ Pc1600

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Category {{
    Pc1500,
    Ce150,
    Ce158,
    Pc1600,
}}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {{
    Statement,
    Function,
    Operator,
    Modifier,
}}

#[derive(Clone, Copy, Debug)]
pub struct Keyword {{
    /// Full upper-case keyword, e.g. "PRINT", "CHR$", "PEEK#".
    pub name: &'static str,
    /// Shortest keyboard prefix; equals `name` when there is no shorter abbreviation.
    pub abbrev: &'static str,
    /// 2-byte ROM token, big-endian, e.g. 0xF097.
    pub code: u16,
    pub category: Category,
    pub kind: Kind,
}}
"""

    body = "\n\n".join(
        [
            emit_slice(
                "PC1500_SET",
                "PC-1500 family pool (PC-1500 core + CE-150 + CE-158), Java pool order.",
                pc1500_set,
            ),
            emit_slice(
                "PC1600_SET",
                "PC-1600 family pool (CE-150 + CE-158 + PC-1600), Java pool order.",
                pc1600_set,
            ),
        ]
    )
    return header + "\n" + body + "\n"


def main() -> int:
    generated = build()
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            sys.stderr.write("src/keywords.rs is out of date; run tools/extract_keywords.py\n")
            return 1
        print("src/keywords.rs is up to date")
        return 0
    OUT.write_text(generated, encoding="utf-8")
    n = generated.count("Keyword { name:")
    print(f"wrote {OUT.relative_to(PROJECT)} ({n} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
